version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "$CONTAINER_NAME"
          ContainerPort: $CONTAINER_PORT
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-0791cd2bcf76a6367
              - subnet-0178f6a61306f3bf1
              - subnet-0d9b5fc54f15c9bcd
            SecurityGroups:
              - sg-0fd97e0b1445a66ee
            AssignPublicIp: "ENABLED"
